package com.github.spencerio1.smm.init;

import net.minecraft.item.Item;

import com.github.spencerio1.smm.SpenceriosModMod;
import com.github.spencerio1.smm.item.armor.ItemSMMArmor;
import com.github.spencerio1.smm.lib.ArmorMaterials;
import com.github.spencerio1.smm.lib.ModInfo;

import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.GameRegistry.ObjectHolder;

/**
 * The file in which all of the Armor is initialized for Spencerio's Mod Mod
 * @author Spencerio
 * @author Parker8283
 * @see net.minecraft.item.Item
 * @see net.minecraft.init.Items
 */
@ObjectHolder(ModInfo.MODID)
public class SMMArmor {
	public static final Item coalHelmet = new ItemSMMArmor(ArmorMaterials.COAL, SpenceriosModMod.proxy.addArmor("coal"), 0).setUnlocalizedName("coalHelmet").setTextureName(ModInfo.MODID + ":" + "coalHelmet").add();
	public static final Item coalChestplate = new ItemSMMArmor(ArmorMaterials.COAL, SpenceriosModMod.proxy.addArmor("coal"), 1).setUnlocalizedName("coalChestplate").setTextureName(ModInfo.MODID + ":" + "coalChestplate").add();
	public static final Item coalLeggings = new ItemSMMArmor(ArmorMaterials.COAL, SpenceriosModMod.proxy.addArmor("coal"), 2).setUnlocalizedName("coalLeggings").setTextureName(ModInfo.MODID + ":" + "coalLeggings").add();
	public static final Item coalBoots = new ItemSMMArmor(ArmorMaterials.COAL, SpenceriosModMod.proxy.addArmor("coal"), 3).setUnlocalizedName("coalBoots").setTextureName(ModInfo.MODID + ":" + "coalBoots").add();
	public static final Item emeraldHelmet = new ItemSMMArmor(ArmorMaterials.EMERALD, SpenceriosModMod.proxy.addArmor("emerald"), 0).setUnlocalizedName("emeraldHelmet").setTextureName(ModInfo.MODID + ":" + "emeraldHelmet").add();
	public static final Item emeraldChestplate = new ItemSMMArmor(ArmorMaterials.EMERALD, SpenceriosModMod.proxy.addArmor("emerald"), 1).setUnlocalizedName("emeraldChestplate").setTextureName(ModInfo.MODID + ":" + "emeraldChestplate").add();
	public static final Item emeraldLeggings = new ItemSMMArmor(ArmorMaterials.EMERALD, SpenceriosModMod.proxy.addArmor("emerald"), 2).setUnlocalizedName("emeraldLeggings").setTextureName(ModInfo.MODID + ":" + "emeraldLeggings").add();
	public static final Item emeraldBoots = new ItemSMMArmor(ArmorMaterials.EMERALD, SpenceriosModMod.proxy.addArmor("emerald"), 3).setUnlocalizedName("emeraldBoots").setTextureName(ModInfo.MODID + ":" + "emeraldBoots").add();
	public static final Item redstoneHelmet = new ItemSMMArmor(ArmorMaterials.REDSTONE, SpenceriosModMod.proxy.addArmor("redstone"), 0).setUnlocalizedName("redstoneHelmet").setTextureName(ModInfo.MODID + ":" + "redstoneHelmet").add();
	public static final Item redstoneChestplate = new ItemSMMArmor(ArmorMaterials.REDSTONE, SpenceriosModMod.proxy.addArmor("redstone"), 1).setUnlocalizedName("redstoneChestplate").setTextureName(ModInfo.MODID + ":" + "redstoneChestplate").add();
	public static final Item redstoneLeggings = new ItemSMMArmor(ArmorMaterials.REDSTONE, SpenceriosModMod.proxy.addArmor("redstone"), 2).setUnlocalizedName("redstoneLeggings").setTextureName(ModInfo.MODID + ":" + "redstoneLeggings").add();
	public static final Item redstoneBoots = new ItemSMMArmor(ArmorMaterials.REDSTONE, SpenceriosModMod.proxy.addArmor("redstone"), 3).setUnlocalizedName("redstoneBoots").setTextureName(ModInfo.MODID + ":" + "redstoneBoots").add();
	public static final Item lapisLazuliHelmet = new ItemSMMArmor(ArmorMaterials.LAPISLAZULI, SpenceriosModMod.proxy.addArmor("lapisLazuli"), 0).setUnlocalizedName("lapisLazuliHelmet").setTextureName(ModInfo.MODID + ":" + "lapisLazuliHelmet").add();
	public static final Item lapisLazuliChestplate = new ItemSMMArmor(ArmorMaterials.LAPISLAZULI, SpenceriosModMod.proxy.addArmor("lapisLazuli"), 1).setUnlocalizedName("lapisLazuliChestplate").setTextureName(ModInfo.MODID + ":" + "lapisLazuliChestplate").add();
	public static final Item lapisLazuliLeggings = new ItemSMMArmor(ArmorMaterials.LAPISLAZULI, SpenceriosModMod.proxy.addArmor("lapisLazuli"), 2).setUnlocalizedName("lapisLazuliLeggings").setTextureName(ModInfo.MODID + ":" + "lapisLazuliLeggings").add();
	public static final Item lapisLazuliBoots = new ItemSMMArmor(ArmorMaterials.LAPISLAZULI, SpenceriosModMod.proxy.addArmor("lapisLazuli"), 3).setUnlocalizedName("lapisLazuliBoots").setTextureName(ModInfo.MODID + ":" + "lapisLazuliBoots").add();
	public static final Item earthQuartzHelmet = new ItemSMMArmor(ArmorMaterials.EARTHQUARTZ, SpenceriosModMod.proxy.addArmor("earthQuartz"), 0).setUnlocalizedName("earthQuartzHelmet").setTextureName(ModInfo.MODID + ":" + "earthQuartzHelmet").add();
	public static final Item earthQuartzChestplate = new ItemSMMArmor(ArmorMaterials.EARTHQUARTZ, SpenceriosModMod.proxy.addArmor("earthQuartz"), 1).setUnlocalizedName("earthQuartzChestplate").setTextureName(ModInfo.MODID + ":" + "earthQuartzChestplate").add();
	public static final Item earthQuartzLeggings = new ItemSMMArmor(ArmorMaterials.EARTHQUARTZ, SpenceriosModMod.proxy.addArmor("earthQuartz"), 2).setUnlocalizedName("earthQuartzLeggings").setTextureName(ModInfo.MODID + ":" + "earthQuartzLeggings").add();
	public static final Item earthQuartzBoots = new ItemSMMArmor(ArmorMaterials.EARTHQUARTZ, SpenceriosModMod.proxy.addArmor("earthQuartz"), 3).setUnlocalizedName("earthQuartzBoots").setTextureName(ModInfo.MODID + ":" + "earthQuartzBoots").add();
	public static final Item copperHelmet = new ItemSMMArmor(ArmorMaterials.COPPER, SpenceriosModMod.proxy.addArmor("copper"), 0).setUnlocalizedName("copperHelmet").setTextureName(ModInfo.MODID + ":" + "copperHelmet").add();
	public static final Item copperChestplate = new ItemSMMArmor(ArmorMaterials.COPPER, SpenceriosModMod.proxy.addArmor("copper"), 1).setUnlocalizedName("copperChestplate").setTextureName(ModInfo.MODID + ":" + "copperChestplate").add();
	public static final Item copperLeggings = new ItemSMMArmor(ArmorMaterials.COPPER, SpenceriosModMod.proxy.addArmor("copper"), 2).setUnlocalizedName("copperLeggings").setTextureName(ModInfo.MODID + ":" + "copperLeggings").add();
	public static final Item copperBoots = new ItemSMMArmor(ArmorMaterials.COPPER, SpenceriosModMod.proxy.addArmor("copper"), 3).setUnlocalizedName("copperBoots").setTextureName(ModInfo.MODID + ":" + "copperBoots").add();
	public static final Item carbonHelmet = new ItemSMMArmor(ArmorMaterials.CARBON, SpenceriosModMod.proxy.addArmor("carbon"), 0).setUnlocalizedName("carbonHelmet").setTextureName(ModInfo.MODID + ":" + "carbonHelmet").add();
	public static final Item carbonChestplate = new ItemSMMArmor(ArmorMaterials.CARBON, SpenceriosModMod.proxy.addArmor("carbon"), 1).setUnlocalizedName("carbonChestplate").setTextureName(ModInfo.MODID + ":" + "carbonChestplate").add();
	public static final Item carbonLeggings = new ItemSMMArmor(ArmorMaterials.CARBON, SpenceriosModMod.proxy.addArmor("carbon"), 2).setUnlocalizedName("carbonLeggings").setTextureName(ModInfo.MODID + ":" + "carbonLeggings").add();
	public static final Item carbonBoots = new ItemSMMArmor(ArmorMaterials.CARBON, SpenceriosModMod.proxy.addArmor("carbon"), 3).setUnlocalizedName("carbonBoots").setTextureName(ModInfo.MODID + ":" + "carbonBoots").add();
	public static final Item silverHelmet = new ItemSMMArmor(ArmorMaterials.SILVER, SpenceriosModMod.proxy.addArmor("silver"), 0).setUnlocalizedName("silverHelmet").setTextureName(ModInfo.MODID + ":" + "silverHelmet").add();
	public static final Item silverChestplate = new ItemSMMArmor(ArmorMaterials.SILVER, SpenceriosModMod.proxy.addArmor("silver"), 1).setUnlocalizedName("silverChestplate").setTextureName(ModInfo.MODID + ":" + "silverChestplate").add();
	public static final Item silverLeggings = new ItemSMMArmor(ArmorMaterials.SILVER, SpenceriosModMod.proxy.addArmor("silver"), 2).setUnlocalizedName("silverLeggings").setTextureName(ModInfo.MODID + ":" + "silverLeggings").add();
	public static final Item silverBoots = new ItemSMMArmor(ArmorMaterials.SILVER, SpenceriosModMod.proxy.addArmor("silver"), 3).setUnlocalizedName("silverBoots").setTextureName(ModInfo.MODID + ":" + "silverBoots").add();
	public static final Item cobaltHelmet = new ItemSMMArmor(ArmorMaterials.COBALT, SpenceriosModMod.proxy.addArmor("cobalt"), 0).setUnlocalizedName("cobaltHelmet").setTextureName(ModInfo.MODID + ":" + "cobaltHelmet").add();
	public static final Item cobaltChestplate = new ItemSMMArmor(ArmorMaterials.COBALT, SpenceriosModMod.proxy.addArmor("cobalt"), 1).setUnlocalizedName("cobaltChestplate").setTextureName(ModInfo.MODID + ":" + "cobaltChestplate").add();
	public static final Item cobaltLeggings = new ItemSMMArmor(ArmorMaterials.COBALT, SpenceriosModMod.proxy.addArmor("cobalt"), 2).setUnlocalizedName("cobaltLeggings").setTextureName(ModInfo.MODID + ":" + "cobaltLeggings").add();
	public static final Item cobaltBoots = new ItemSMMArmor(ArmorMaterials.COBALT, SpenceriosModMod.proxy.addArmor("cobalt"), 3).setUnlocalizedName("cobaltBoots").setTextureName(ModInfo.MODID + ":" + "cobaltBoots").add();
	public static final Item rubyHelmet = new ItemSMMArmor(ArmorMaterials.RUBY, SpenceriosModMod.proxy.addArmor("ruby"), 0).setUnlocalizedName("rubyHelmet").setTextureName(ModInfo.MODID + ":" + "rubyHelmet").add();
	public static final Item rubyChestplate = new ItemSMMArmor(ArmorMaterials.RUBY, SpenceriosModMod.proxy.addArmor("ruby"), 1).setUnlocalizedName("rubyChestplate").setTextureName(ModInfo.MODID + ":" + "rubyChestplate").add();
	public static final Item rubyLeggings = new ItemSMMArmor(ArmorMaterials.RUBY, SpenceriosModMod.proxy.addArmor("ruby"), 2).setUnlocalizedName("rubyLeggings").setTextureName(ModInfo.MODID + ":" + "rubyLeggings").add();
	public static final Item rubyBoots = new ItemSMMArmor(ArmorMaterials.RUBY, SpenceriosModMod.proxy.addArmor("ruby"), 3).setUnlocalizedName("rubyBoots").setTextureName(ModInfo.MODID + ":" + "rubyBoots").add();
	public static final Item titaniumHelmet = new ItemSMMArmor(ArmorMaterials.TITANIUM, SpenceriosModMod.proxy.addArmor("titanium"), 0).setUnlocalizedName("titaniumHelmet").setTextureName(ModInfo.MODID + ":" + "titaniumHelmet").add();
	public static final Item titaniumChestplate = new ItemSMMArmor(ArmorMaterials.TITANIUM, SpenceriosModMod.proxy.addArmor("titanium"), 1).setUnlocalizedName("titaniumChestplate").setTextureName(ModInfo.MODID + ":" + "titaniumChestplate").add();
	public static final Item titaniumLeggings = new ItemSMMArmor(ArmorMaterials.TITANIUM, SpenceriosModMod.proxy.addArmor("titanium"), 2).setUnlocalizedName("titaniumLeggings").setTextureName(ModInfo.MODID + ":" + "titaniumLeggings").add();
	public static final Item titaniumBoots = new ItemSMMArmor(ArmorMaterials.TITANIUM, SpenceriosModMod.proxy.addArmor("titanium"), 3).setUnlocalizedName("titaniumBoots").setTextureName(ModInfo.MODID + ":" + "titaniumBoots").add();
	public static final Item hellishHelmet = new ItemSMMArmor(ArmorMaterials.HELLISH, SpenceriosModMod.proxy.addArmor("hellish"), 0).setUnlocalizedName("hellishHelmet").setTextureName(ModInfo.MODID + ":" + "hellishHelmet").add();
	public static final Item hellishChestplate = new ItemSMMArmor(ArmorMaterials.HELLISH, SpenceriosModMod.proxy.addArmor("hellish"), 1).setUnlocalizedName("hellishChestplate").setTextureName(ModInfo.MODID + ":" + "hellishChestplate").add();
	public static final Item hellishLeggings = new ItemSMMArmor(ArmorMaterials.HELLISH, SpenceriosModMod.proxy.addArmor("hellish"), 2).setUnlocalizedName("hellishLeggings").setTextureName(ModInfo.MODID + ":" + "hellishLeggings").add();
	public static final Item hellishBoots = new ItemSMMArmor(ArmorMaterials.HELLISH, SpenceriosModMod.proxy.addArmor("hellish"), 3).setUnlocalizedName("hellishBoots").setTextureName(ModInfo.MODID + ":" + "hellishBoots").add();
	public static final Item leadHelmet = new ItemSMMArmor(ArmorMaterials.LEAD, SpenceriosModMod.proxy.addArmor("lead"), 0).setUnlocalizedName("leadHelmet").setTextureName(ModInfo.MODID + ":" + "leadHelmet").add();
	public static final Item leadChestplate = new ItemSMMArmor(ArmorMaterials.LEAD, SpenceriosModMod.proxy.addArmor("lead"), 1).setUnlocalizedName("leadChestplate").setTextureName(ModInfo.MODID + ":" + "leadChestplate").add();
	public static final Item leadLeggings = new ItemSMMArmor(ArmorMaterials.LEAD, SpenceriosModMod.proxy.addArmor("lead"), 2).setUnlocalizedName("leadLeggings").setTextureName(ModInfo.MODID + ":" + "leadLeggings").add();
	public static final Item leadBoots = new ItemSMMArmor(ArmorMaterials.LEAD, SpenceriosModMod.proxy.addArmor("lead"), 3).setUnlocalizedName("leadBoots").setTextureName(ModInfo.MODID + ":" + "leadBoots").add();
	public static final Item obsidianHelmet = new ItemSMMArmor(ArmorMaterials.OBSIDIAN, SpenceriosModMod.proxy.addArmor("obsidian"), 0).setUnlocalizedName("obsidianHelmet").setTextureName(ModInfo.MODID + ":" + "obsidianHelmet").add();
	public static final Item obsidianChestplate = new ItemSMMArmor(ArmorMaterials.OBSIDIAN, SpenceriosModMod.proxy.addArmor("obsidian"), 1).setUnlocalizedName("obsidianChestplate").setTextureName(ModInfo.MODID + ":" + "obsidianChestplate").add();
	public static final Item obsidianLeggings = new ItemSMMArmor(ArmorMaterials.OBSIDIAN, SpenceriosModMod.proxy.addArmor("obsidian"), 2).setUnlocalizedName("obsidianLeggings").setTextureName(ModInfo.MODID + ":" + "obsidianLeggings").add();
	public static final Item obsidianBoots = new ItemSMMArmor(ArmorMaterials.OBSIDIAN, SpenceriosModMod.proxy.addArmor("obsidian"), 3).setUnlocalizedName("obsidianBoots").setTextureName(ModInfo.MODID + ":" + "obsidianBoots").add();
	public static final Item endStoneHelmet = new ItemSMMArmor(ArmorMaterials.ENDSTONE, SpenceriosModMod.proxy.addArmor("endStone"), 0).setUnlocalizedName("endStoneHelmet").setTextureName(ModInfo.MODID + ":" + "endStoneHelmet").add();
	public static final Item endStoneChestplate = new ItemSMMArmor(ArmorMaterials.ENDSTONE, SpenceriosModMod.proxy.addArmor("endStone"), 1).setUnlocalizedName("endStoneChestplate").setTextureName(ModInfo.MODID + ":" + "endStoneChestplate").add();
	public static final Item endStoneLeggings = new ItemSMMArmor(ArmorMaterials.ENDSTONE, SpenceriosModMod.proxy.addArmor("endStone"), 2).setUnlocalizedName("endStoneLeggings").setTextureName(ModInfo.MODID + ":" + "endStoneLeggings").add();
	public static final Item endStoneBoots = new ItemSMMArmor(ArmorMaterials.ENDSTONE, SpenceriosModMod.proxy.addArmor("endStone"), 3).setUnlocalizedName("endStoneBoots").setTextureName(ModInfo.MODID + ":" + "endStoneBoots").add();
	public static final Item cobblestoneHelmet = new ItemSMMArmor(ArmorMaterials.COBBLESTONE, SpenceriosModMod.proxy.addArmor("cobblestone"), 0).setUnlocalizedName("cobblestoneHelmet").setTextureName(ModInfo.MODID + ":" + "cobblestoneHelmet").add();
	public static final Item cobblestoneChestplate = new ItemSMMArmor(ArmorMaterials.COBBLESTONE, SpenceriosModMod.proxy.addArmor("cobblestone"), 1).setUnlocalizedName("cobblestoneChestplate").setTextureName(ModInfo.MODID + ":" + "cobblestoneChestplate").add();
	public static final Item cobblestoneLeggings = new ItemSMMArmor(ArmorMaterials.COBBLESTONE, SpenceriosModMod.proxy.addArmor("cobblestone"), 2).setUnlocalizedName("cobblestoneLeggings").setTextureName(ModInfo.MODID + ":" + "cobblestoneLeggings").add();
	public static final Item cobblestoneBoots = new ItemSMMArmor(ArmorMaterials.COBBLESTONE, SpenceriosModMod.proxy.addArmor("cobblestone"), 3).setUnlocalizedName("cobblestoneBoots").setTextureName(ModInfo.MODID + ":" + "cobblestoneBoots").add();
	public static final Item woodHelmet = new ItemSMMArmor(ArmorMaterials.WOOD, SpenceriosModMod.proxy.addArmor("wood"), 0).setUnlocalizedName("woodHelmet").setTextureName(ModInfo.MODID + ":" + "woodHelmet").add();
	public static final Item woodChestplate = new ItemSMMArmor(ArmorMaterials.WOOD, SpenceriosModMod.proxy.addArmor("wood"), 1).setUnlocalizedName("woodChestplate").setTextureName(ModInfo.MODID + ":" + "woodChestplate").add();
	public static final Item woodLeggings = new ItemSMMArmor(ArmorMaterials.WOOD, SpenceriosModMod.proxy.addArmor("wood"), 2).setUnlocalizedName("woodLeggings").setTextureName(ModInfo.MODID + ":" + "woodLeggings").add();
	public static final Item woodBoots = new ItemSMMArmor(ArmorMaterials.WOOD, SpenceriosModMod.proxy.addArmor("wood"), 3).setUnlocalizedName("woodBoots").setTextureName(ModInfo.MODID + ":" + "woodBoots").add();
	public static final Item sapphireHelmet = new ItemSMMArmor(ArmorMaterials.SAPPHIRE, SpenceriosModMod.proxy.addArmor("sapphire"), 0).setUnlocalizedName("sapphireHelmet").setTextureName(ModInfo.MODID + ":" + "sapphireHelmet").add();
	public static final Item sapphireChestplate = new ItemSMMArmor(ArmorMaterials.SAPPHIRE, SpenceriosModMod.proxy.addArmor("sapphire"), 1).setUnlocalizedName("sapphireChestplate").setTextureName(ModInfo.MODID + ":" + "sapphireChestplate").add();
	public static final Item sapphireLeggings = new ItemSMMArmor(ArmorMaterials.SAPPHIRE, SpenceriosModMod.proxy.addArmor("sapphire"), 2).setUnlocalizedName("sapphireLeggings").setTextureName(ModInfo.MODID + ":" + "sapphireLeggings").add();
	public static final Item sapphireBoots = new ItemSMMArmor(ArmorMaterials.SAPPHIRE, SpenceriosModMod.proxy.addArmor("sapphire"), 3).setUnlocalizedName("sapphireBoots").setTextureName(ModInfo.MODID + ":" + "sapphireBoots").add();
	public static final Item topazHelmet = new ItemSMMArmor(ArmorMaterials.TOPAZ, SpenceriosModMod.proxy.addArmor("topaz"), 0).setUnlocalizedName("topazHelmet").setTextureName(ModInfo.MODID + ":" + "topazHelmet").add();
	public static final Item topazChestplate = new ItemSMMArmor(ArmorMaterials.TOPAZ, SpenceriosModMod.proxy.addArmor("topaz"), 1).setUnlocalizedName("topazChestplate").setTextureName(ModInfo.MODID + ":" + "topazChestplate").add();
	public static final Item topazLeggings = new ItemSMMArmor(ArmorMaterials.TOPAZ, SpenceriosModMod.proxy.addArmor("topaz"), 2).setUnlocalizedName("topazLeggings").setTextureName(ModInfo.MODID + ":" + "topazLeggings").add();
	public static final Item topazBoots = new ItemSMMArmor(ArmorMaterials.TOPAZ, SpenceriosModMod.proxy.addArmor("topaz"), 3).setUnlocalizedName("topazBoots").setTextureName(ModInfo.MODID + ":" + "topazBoots").add();
	public static final Item jadeHelmet = new ItemSMMArmor(ArmorMaterials.JADE, SpenceriosModMod.proxy.addArmor("jade"), 0).setUnlocalizedName("jadeHelmet").setTextureName(ModInfo.MODID + ":" + "jadeHelmet").add();
	public static final Item jadeChestplate = new ItemSMMArmor(ArmorMaterials.JADE, SpenceriosModMod.proxy.addArmor("jade"), 1).setUnlocalizedName("jadeChestplate").setTextureName(ModInfo.MODID + ":" + "jadeChestplate").add();
	public static final Item jadeLeggings = new ItemSMMArmor(ArmorMaterials.JADE, SpenceriosModMod.proxy.addArmor("jade"), 2).setUnlocalizedName("jadeLeggings").setTextureName(ModInfo.MODID + ":" + "jadeLeggings").add();
	public static final Item jadeBoots = new ItemSMMArmor(ArmorMaterials.JADE, SpenceriosModMod.proxy.addArmor("jade"), 3).setUnlocalizedName("jadeBoots").setTextureName(ModInfo.MODID + ":" + "jadeBoots").add();
	public static final Item steelHelmet = new ItemSMMArmor(ArmorMaterials.STEEL, SpenceriosModMod.proxy.addArmor("steel"), 0).setUnlocalizedName("steelHelmet").setTextureName(ModInfo.MODID + ":" + "steelHelmet").add();
	public static final Item steelChestplate = new ItemSMMArmor(ArmorMaterials.STEEL, SpenceriosModMod.proxy.addArmor("steel"), 1).setUnlocalizedName("steelChestplate").setTextureName(ModInfo.MODID + ":" + "steelChestplate").add();
	public static final Item steelLeggings = new ItemSMMArmor(ArmorMaterials.STEEL, SpenceriosModMod.proxy.addArmor("steel"), 2).setUnlocalizedName("steelLeggings").setTextureName(ModInfo.MODID + ":" + "steelLeggings").add();
	public static final Item steelBoots = new ItemSMMArmor(ArmorMaterials.STEEL, SpenceriosModMod.proxy.addArmor("steel"), 3).setUnlocalizedName("steelBoots").setTextureName(ModInfo.MODID + ":" + "steelBoots").add();
	public static final Item tanzaniteHelmet = new ItemSMMArmor(ArmorMaterials.TANZANITE, SpenceriosModMod.proxy.addArmor("steel"), 0).setUnlocalizedName("tanzaniteHelmet").setTextureName(ModInfo.MODID + ":" + "tanzaniteHelmet").add();
	public static final Item tanzaniteChestplate = new ItemSMMArmor(ArmorMaterials.TANZANITE, SpenceriosModMod.proxy.addArmor("steel"), 1).setUnlocalizedName("tanzaniteChestplate").setTextureName(ModInfo.MODID + ":" + "tanzaniteChestplate").add();
	public static final Item tanzaniteLeggings = new ItemSMMArmor(ArmorMaterials.TANZANITE, SpenceriosModMod.proxy.addArmor("steel"), 2).setUnlocalizedName("tanzaniteLeggings").setTextureName(ModInfo.MODID + ":" + "tanzaniteLeggings").add();
	public static final Item tanzaniteBoots = new ItemSMMArmor(ArmorMaterials.TANZANITE, SpenceriosModMod.proxy.addArmor("steel"), 3).setUnlocalizedName("tanzaniteBoots").setTextureName(ModInfo.MODID + ":" + "tanzaniteBoots").add();
	public static final Item apatiteHelmet = new ItemSMMArmor(ArmorMaterials.APATITE, SpenceriosModMod.proxy.addArmor("apatite"), 0).setUnlocalizedName("apatiteHelmet").setTextureName(ModInfo.MODID + ":" + "apatiteHelmet").add();
	public static final Item apatiteChestplate = new ItemSMMArmor(ArmorMaterials.APATITE, SpenceriosModMod.proxy.addArmor("apatite"), 1).setUnlocalizedName("apatiteChestplate").setTextureName(ModInfo.MODID + ":" + "apatiteChestplate").add();
	public static final Item apatiteLeggings = new ItemSMMArmor(ArmorMaterials.APATITE, SpenceriosModMod.proxy.addArmor("apatite"), 2).setUnlocalizedName("apatiteLeggings").setTextureName(ModInfo.MODID + ":" + "apatiteLeggings").add();
	public static final Item apatiteBoots = new ItemSMMArmor(ArmorMaterials.APATITE, SpenceriosModMod.proxy.addArmor("apatite"), 3).setUnlocalizedName("apatiteBoots").setTextureName(ModInfo.MODID + ":" + "apatiteBoots").add();
	public static final Item netherQuartzHelmet = new ItemSMMArmor(ArmorMaterials.NETHERQUARTZ, SpenceriosModMod.proxy.addArmor("netherQuartz"), 0).setUnlocalizedName("netherQuartzHelmet").setTextureName(ModInfo.MODID + ":" + "netherQuartzHelmet").add();
	public static final Item netherQuartzChestplate = new ItemSMMArmor(ArmorMaterials.NETHERQUARTZ, SpenceriosModMod.proxy.addArmor("netherQuartz"), 1).setUnlocalizedName("netherQuartzChestplate").setTextureName(ModInfo.MODID + ":" + "netherQuartzChestplate").add();
	public static final Item netherQuartzLeggings = new ItemSMMArmor(ArmorMaterials.NETHERQUARTZ, SpenceriosModMod.proxy.addArmor("netherQuartz"), 2).setUnlocalizedName("netherQuartzLeggings").setTextureName(ModInfo.MODID + ":" + "netherQuartzLeggings").add();
	public static final Item netherQuartzBoots = new ItemSMMArmor(ArmorMaterials.NETHERQUARTZ, SpenceriosModMod.proxy.addArmor("netherQuartz"), 3).setUnlocalizedName("netherQuartzBoots").setTextureName(ModInfo.MODID + ":" + "netherQuartzBoots").add();
	public static final Item amethystHelmet = new ItemSMMArmor(ArmorMaterials.AMETHYST, SpenceriosModMod.proxy.addArmor("amethyst"), 0).setUnlocalizedName("amethystHelmet").setTextureName(ModInfo.MODID + ":" + "amethystHelmet").add();
	public static final Item amethystChestplate = new ItemSMMArmor(ArmorMaterials.AMETHYST, SpenceriosModMod.proxy.addArmor("amethyst"), 1).setUnlocalizedName("amethystChestplate").setTextureName(ModInfo.MODID + ":" + "amethystChestplate").add();
	public static final Item amethystLeggings = new ItemSMMArmor(ArmorMaterials.AMETHYST, SpenceriosModMod.proxy.addArmor("amethyst"), 2).setUnlocalizedName("amethystLeggings").setTextureName(ModInfo.MODID + ":" + "amethystLeggings").add();
	public static final Item amethystBoots = new ItemSMMArmor(ArmorMaterials.AMETHYST, SpenceriosModMod.proxy.addArmor("amethyst"), 3).setUnlocalizedName("amethystBoots").setTextureName(ModInfo.MODID + ":" + "amethystBoots").add();
	
	public static void initArmor()
	{
		GameRegistry.registerItem(coalHelmet, coalHelmet.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(coalChestplate, coalChestplate.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(coalLeggings, coalLeggings.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(coalBoots, coalBoots.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(emeraldHelmet, emeraldHelmet.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(emeraldChestplate, emeraldChestplate.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(emeraldLeggings, emeraldLeggings.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(emeraldBoots, emeraldBoots.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(redstoneHelmet, redstoneHelmet.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(redstoneChestplate, redstoneChestplate.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(redstoneLeggings, redstoneLeggings.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(redstoneBoots, redstoneBoots.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(lapisLazuliHelmet, lapisLazuliHelmet.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(lapisLazuliChestplate, lapisLazuliChestplate.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(lapisLazuliLeggings, lapisLazuliLeggings.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(lapisLazuliBoots, lapisLazuliBoots.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(earthQuartzHelmet, earthQuartzHelmet.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(earthQuartzChestplate, earthQuartzChestplate.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(earthQuartzLeggings, earthQuartzLeggings.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(earthQuartzBoots, earthQuartzBoots.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(copperHelmet, copperHelmet.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(copperChestplate, copperChestplate.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(copperLeggings, copperLeggings.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(copperBoots, copperBoots.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(carbonHelmet, carbonHelmet.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(carbonChestplate, carbonChestplate.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(carbonLeggings, carbonLeggings.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(carbonBoots, carbonBoots.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(silverHelmet, silverHelmet.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(silverChestplate, silverChestplate.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(silverLeggings, silverLeggings.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(silverBoots, silverBoots.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(cobaltHelmet, cobaltHelmet.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(cobaltChestplate, cobaltChestplate.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(cobaltLeggings, cobaltLeggings.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(cobaltBoots, cobaltBoots.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(rubyHelmet, rubyHelmet.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(rubyChestplate, rubyChestplate.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(rubyLeggings, rubyLeggings.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(rubyBoots, rubyBoots.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(titaniumHelmet, titaniumHelmet.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(titaniumChestplate, titaniumChestplate.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(titaniumLeggings, titaniumLeggings.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(titaniumBoots, titaniumBoots.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(hellishHelmet, hellishHelmet.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(hellishChestplate, hellishChestplate.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(hellishLeggings, hellishLeggings.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(hellishBoots, hellishBoots.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(leadHelmet, leadHelmet.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(leadChestplate, leadChestplate.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(leadLeggings, leadLeggings.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(leadBoots, leadBoots.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(obsidianHelmet, obsidianHelmet.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(obsidianChestplate, obsidianChestplate.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(obsidianLeggings, obsidianLeggings.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(obsidianBoots, obsidianBoots.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(endStoneHelmet, endStoneHelmet.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(endStoneChestplate, endStoneChestplate.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(endStoneLeggings, endStoneLeggings.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(endStoneBoots, endStoneBoots.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(cobblestoneHelmet, cobblestoneHelmet.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(cobblestoneChestplate, cobblestoneChestplate.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(cobblestoneLeggings, cobblestoneLeggings.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(cobblestoneBoots, cobblestoneBoots.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(woodHelmet, woodHelmet.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(woodChestplate, woodChestplate.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(woodLeggings, woodLeggings.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(woodBoots, woodBoots.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(sapphireHelmet, sapphireHelmet.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(sapphireChestplate, sapphireChestplate.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(sapphireLeggings, sapphireLeggings.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(sapphireBoots, sapphireBoots.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(topazHelmet, topazHelmet.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(topazChestplate, topazChestplate.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(topazLeggings, topazLeggings.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(topazBoots, topazBoots.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(jadeHelmet, jadeHelmet.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(jadeChestplate, jadeChestplate.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(jadeLeggings, jadeLeggings.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(jadeBoots, jadeBoots.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(steelHelmet, steelHelmet.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(steelChestplate, steelChestplate.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(steelLeggings, steelLeggings.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(steelBoots, steelBoots.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(tanzaniteHelmet, tanzaniteHelmet.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(tanzaniteChestplate, tanzaniteChestplate.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(tanzaniteLeggings, tanzaniteLeggings.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(tanzaniteBoots, tanzaniteBoots.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(apatiteHelmet, apatiteHelmet.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(apatiteChestplate, apatiteChestplate.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(apatiteLeggings, apatiteLeggings.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(apatiteBoots, apatiteBoots.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(netherQuartzHelmet, netherQuartzHelmet.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(netherQuartzChestplate, netherQuartzChestplate.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(netherQuartzLeggings, netherQuartzLeggings.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(netherQuartzBoots, netherQuartzBoots.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(amethystHelmet, amethystHelmet.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(amethystChestplate, amethystChestplate.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(amethystLeggings, amethystLeggings.getUnlocalizedName().substring(9));
		GameRegistry.registerItem(amethystBoots, amethystBoots.getUnlocalizedName().substring(9));
	}
}
