package com.github.spencerio1.smm.init;

import net.minecraft.item.Item;

import com.github.spencerio1.smm.item.tools.ItemSMMAxe;
import com.github.spencerio1.smm.item.tools.ItemSMMHoe;
import com.github.spencerio1.smm.item.tools.ItemSMMPickaxe;
import com.github.spencerio1.smm.item.tools.ItemSMMShovel;
import com.github.spencerio1.smm.item.tools.ItemSMMSword;
import com.github.spencerio1.smm.lib.Reference;
import com.github.spencerio1.smm.lib.ToolMaterials;

import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.GameRegistry.ObjectHolder;

/**
 * The file in which all of the Tools are initialized for Spencerio's Mod Mod
 * @author Spencerio
 * @author Parker8283
 * @see net.minecraft.item.Item
 * @see net.minecraft.init.Items
 */
@ObjectHolder(Reference.MODID)
public class SMMTools {	
	public static final Item coalPickaxe = new ItemSMMPickaxe(ToolMaterials.COAL).setUnlocalizedName("coalPickaxe").setTextureName(Reference.MODID + ":" + "coalPickaxe").add();
	public static final Item coalAxe = new ItemSMMAxe(ToolMaterials.COAL).setUnlocalizedName("coalAxe").setTextureName(Reference.MODID + ":" + "coalAxe").add();
	public static final Item coalShovel = new ItemSMMShovel(ToolMaterials.COAL).setUnlocalizedName("coalShovel").setTextureName(Reference.MODID + ":" + "coalShovel").add();
	public static final Item coalHoe = new ItemSMMHoe(ToolMaterials.COAL).setUnlocalizedName("coalHoe").setTextureName(Reference.MODID + ":" + "coalHoe").add();
	public static final Item coalSword = new ItemSMMSword(ToolMaterials.COAL).setUnlocalizedName("coalSword").setTextureName(Reference.MODID + ":" + "coalSword").add();
	public static final Item emeraldPickaxe = new ItemSMMPickaxe(ToolMaterials.EMERALD).setUnlocalizedName("emeraldPickaxe").setTextureName(Reference.MODID + ":" + "emeraldPickaxe").add();
	public static final Item emeraldAxe = new ItemSMMAxe(ToolMaterials.EMERALD).setUnlocalizedName("emeraldAxe").setTextureName(Reference.MODID + ":" + "emeraldAxe").add();
	public static final Item emeraldShovel = new ItemSMMShovel(ToolMaterials.EMERALD).setUnlocalizedName("emeraldShovel").setTextureName(Reference.MODID + ":" + "emeraldShovel").add();
	public static final Item emeraldHoe = new ItemSMMHoe(ToolMaterials.EMERALD).setUnlocalizedName("emeraldHoe").setTextureName(Reference.MODID + ":" + "emeraldHoe").add();
	public static final Item emeraldSword = new ItemSMMSword(ToolMaterials.EMERALD).setUnlocalizedName("emeraldSword").setTextureName(Reference.MODID + ":" + "emeraldSword").add();
	public static final Item redstonePickaxe = new ItemSMMPickaxe(ToolMaterials.REDSTONE).setUnlocalizedName("redstonePickaxe").setTextureName(Reference.MODID + ":" + "redstonePickaxe").add();
	public static final Item redstoneAxe = new ItemSMMAxe(ToolMaterials.REDSTONE).setUnlocalizedName("redstoneAxe").setTextureName(Reference.MODID + ":" + "redstoneAxe").add();
	public static final Item redstoneShovel = new ItemSMMShovel(ToolMaterials.REDSTONE).setUnlocalizedName("redstoneShovel").setTextureName(Reference.MODID + ":" + "redstoneShovel").add();
	public static final Item redstoneHoe = new ItemSMMHoe(ToolMaterials.REDSTONE).setUnlocalizedName("redstoneHoe").setTextureName(Reference.MODID + ":" + "redstoneHoe").add();
	public static final Item redstoneSword = new ItemSMMSword(ToolMaterials.REDSTONE).setUnlocalizedName("redstoneSword").setTextureName(Reference.MODID + ":" + "redstoneSword").add();
	public static final Item lapisLazuliPickaxe = new ItemSMMPickaxe(ToolMaterials.LAPISLAZULI).setUnlocalizedName("lapisLazuliPickaxe").setTextureName(Reference.MODID + ":" + "lapisLazuliPickaxe").add();
	public static final Item lapisLazuliAxe = new ItemSMMAxe(ToolMaterials.LAPISLAZULI).setUnlocalizedName("lapisLazuliAxe").setTextureName(Reference.MODID + ":" + "lapisLazuliAxe").add();
	public static final Item lapisLazuliShovel = new ItemSMMShovel(ToolMaterials.LAPISLAZULI).setUnlocalizedName("lapisLazuliShovel").setTextureName(Reference.MODID + ":" + "lapisLazuliShovel").add();
	public static final Item lapisLazuliHoe = new ItemSMMHoe(ToolMaterials.LAPISLAZULI).setUnlocalizedName("lapisLazuliHoe").setTextureName(Reference.MODID + ":" + "lapisLazuliHoe").add();
	public static final Item lapisLazuliSword = new ItemSMMSword(ToolMaterials.LAPISLAZULI).setUnlocalizedName("lapisLazuliSword").setTextureName(Reference.MODID + ":" + "lapisLazuliSword").add();
	public static final Item earthQuartzPickaxe = new ItemSMMPickaxe(ToolMaterials.EARTHQUARTZ).setUnlocalizedName("earthQuartzPickaxe").setTextureName(Reference.MODID + ":" + "earthQuartzPickaxe").add();
	public static final Item earthQuartzAxe = new ItemSMMAxe(ToolMaterials.EARTHQUARTZ).setUnlocalizedName("earthQuartzAxe").setTextureName(Reference.MODID + ":" + "earthQuartzAxe").add();
	public static final Item earthQuartzShovel = new ItemSMMShovel(ToolMaterials.EARTHQUARTZ).setUnlocalizedName("earthQuartzShovel").setTextureName(Reference.MODID + ":" + "earthQuartzShovel").add();
	public static final Item earthQuartzHoe = new ItemSMMHoe(ToolMaterials.EARTHQUARTZ).setUnlocalizedName("earthQuartzHoe").setTextureName(Reference.MODID + ":" + "earthQuartzHoe").add();
	public static final Item earthQuartzSword = new ItemSMMSword(ToolMaterials.EARTHQUARTZ).setUnlocalizedName("earthQuartzSword").setTextureName(Reference.MODID + ":" + "earthQuartzSword").add();
	public static final Item copperPickaxe = new ItemSMMPickaxe(ToolMaterials.COPPER).setUnlocalizedName("copperPickaxe").setTextureName(Reference.MODID + ":" + "copperPickaxe").add();
	public static final Item copperAxe = new ItemSMMAxe(ToolMaterials.COPPER).setUnlocalizedName("copperAxe").setTextureName(Reference.MODID + ":" + "copperAxe").add();
	public static final Item copperShovel = new ItemSMMShovel(ToolMaterials.COPPER).setUnlocalizedName("copperShovel").setTextureName(Reference.MODID + ":" + "copperShovel").add();
	public static final Item copperHoe = new ItemSMMHoe(ToolMaterials.COPPER).setUnlocalizedName("copperHoe").setTextureName(Reference.MODID + ":" + "copperHoe").add();
	public static final Item copperSword = new ItemSMMSword(ToolMaterials.COPPER).setUnlocalizedName("copperSword").setTextureName(Reference.MODID + ":" + "copperSword").add();
	public static final Item carbonPickaxe = new ItemSMMPickaxe(ToolMaterials.CARBON).setUnlocalizedName("carbonPickaxe").setTextureName(Reference.MODID + ":" + "carbonPickaxe").add();
	public static final Item carbonAxe = new ItemSMMAxe(ToolMaterials.CARBON).setUnlocalizedName("carbonAxe").setTextureName(Reference.MODID + ":" + "carbonAxe").add();
	public static final Item carbonShovel = new ItemSMMShovel(ToolMaterials.CARBON).setUnlocalizedName("carbonShovel").setTextureName(Reference.MODID + ":" + "carbonShovel").add();
	public static final Item carbonHoe = new ItemSMMHoe(ToolMaterials.CARBON).setUnlocalizedName("carbonHoe").setTextureName(Reference.MODID + ":" + "carbonHoe").add();
	public static final Item carbonSword = new ItemSMMSword(ToolMaterials.CARBON).setUnlocalizedName("carbonSword").setTextureName(Reference.MODID + ":" + "carbonSword").add();
	public static final Item silverPickaxe = new ItemSMMPickaxe(ToolMaterials.SILVER).setUnlocalizedName("silverPickaxe").setTextureName(Reference.MODID + ":" + "silverPickaxe").add();
	public static final Item silverAxe = new ItemSMMAxe(ToolMaterials.SILVER).setUnlocalizedName("silverAxe").setTextureName(Reference.MODID + ":" + "silverAxe").add();
	public static final Item silverShovel = new ItemSMMShovel(ToolMaterials.SILVER).setUnlocalizedName("silverShovel").setTextureName(Reference.MODID + ":" + "silverShovel").add();
	public static final Item silverHoe = new ItemSMMHoe(ToolMaterials.SILVER).setUnlocalizedName("silverHoe").setTextureName(Reference.MODID + ":" + "silverHoe").add();
	public static final Item silverSword = new ItemSMMSword(ToolMaterials.SILVER).setUnlocalizedName("silverSword").setTextureName(Reference.MODID + ":" + "silverSword").add();
	public static final Item cobaltPickaxe = new ItemSMMPickaxe(ToolMaterials.COBALT).setUnlocalizedName("cobaltPickaxe").setTextureName(Reference.MODID + ":" + "cobaltPickaxe").add();
	public static final Item cobaltAxe = new ItemSMMAxe(ToolMaterials.COBALT).setUnlocalizedName("cobaltAxe").setTextureName(Reference.MODID + ":" + "cobaltAxe").add();
	public static final Item cobaltShovel = new ItemSMMShovel(ToolMaterials.COBALT).setUnlocalizedName("cobaltShovel").setTextureName(Reference.MODID + ":" + "cobaltShovel").add();
	public static final Item cobaltHoe = new ItemSMMHoe(ToolMaterials.COBALT).setUnlocalizedName("cobaltHoe").setTextureName(Reference.MODID + ":" + "cobaltHoe").add();
	public static final Item cobaltSword = new ItemSMMSword(ToolMaterials.COBALT).setUnlocalizedName("cobaltSword").setTextureName(Reference.MODID + ":" + "cobaltSword").add();
	public static final Item rubyPickaxe = new ItemSMMPickaxe(ToolMaterials.RUBY).setUnlocalizedName("rubyPickaxe").setTextureName(Reference.MODID + ":" + "rubyPickaxe").add();
	public static final Item rubyAxe = new ItemSMMAxe(ToolMaterials.RUBY).setUnlocalizedName("rubyAxe").setTextureName(Reference.MODID + ":" + "rubyAxe").add();
	public static final Item rubyShovel = new ItemSMMShovel(ToolMaterials.RUBY).setUnlocalizedName("rubyShovel").setTextureName(Reference.MODID + ":" + "rubyShovel").add();
	public static final Item rubyHoe = new ItemSMMHoe(ToolMaterials.RUBY).setUnlocalizedName("rubyHoe").setTextureName(Reference.MODID + ":" + "rubyHoe").add();
	public static final Item rubySword = new ItemSMMSword(ToolMaterials.RUBY).setUnlocalizedName("rubySword").setTextureName(Reference.MODID + ":" + "rubySword").add();
	public static final Item titaniumPickaxe = new ItemSMMPickaxe(ToolMaterials.TITANIUM).setUnlocalizedName("titaniumPickaxe").setTextureName(Reference.MODID + ":" + "titaniumPickaxe").add();
	public static final Item titaniumAxe = new ItemSMMAxe(ToolMaterials.TITANIUM).setUnlocalizedName("titaniumAxe").setTextureName(Reference.MODID + ":" + "titaniumAxe").add();
	public static final Item titaniumShovel = new ItemSMMShovel(ToolMaterials.TITANIUM).setUnlocalizedName("titaniumShovel").setTextureName(Reference.MODID + ":" + "titaniumShovel").add();
	public static final Item titaniumHoe = new ItemSMMHoe(ToolMaterials.TITANIUM).setUnlocalizedName("titaniumHoe").setTextureName(Reference.MODID + ":" + "titaniumHoe").add();
	public static final Item titaniumSword = new ItemSMMSword(ToolMaterials.TITANIUM).setUnlocalizedName("titaniumSword").setTextureName(Reference.MODID + ":" + "titaniumSword").add();
	public static final Item hellishPickaxe = new ItemSMMPickaxe(ToolMaterials.HELLISH).setUnlocalizedName("hellishPickaxe").setTextureName(Reference.MODID + ":" + "hellishPickaxe").add();
	public static final Item hellishAxe = new ItemSMMAxe(ToolMaterials.HELLISH).setUnlocalizedName("hellishAxe").setTextureName(Reference.MODID + ":" + "hellishAxe").add();
	public static final Item hellishShovel = new ItemSMMShovel(ToolMaterials.HELLISH).setUnlocalizedName("hellishShovel").setTextureName(Reference.MODID + ":" + "hellishShovel").add();
	public static final Item hellishHoe = new ItemSMMHoe(ToolMaterials.HELLISH).setUnlocalizedName("hellishHoe").setTextureName(Reference.MODID + ":" + "hellishHoe").add();
	public static final Item hellishSword = new ItemSMMSword(ToolMaterials.HELLISH).setUnlocalizedName("hellishSword").setTextureName(Reference.MODID + ":" + "hellishSword").add();
	public static final Item leadPickaxe = new ItemSMMPickaxe(ToolMaterials.LEAD).setUnlocalizedName("leadPickaxe").setTextureName(Reference.MODID + ":" + "leadPickaxe").add();
	public static final Item leadAxe = new ItemSMMAxe(ToolMaterials.LEAD).setUnlocalizedName("leadAxe").setTextureName(Reference.MODID + ":" + "leadAxe").add();
	public static final Item leadShovel = new ItemSMMShovel(ToolMaterials.LEAD).setUnlocalizedName("leadShovel").setTextureName(Reference.MODID + ":" + "leadShovel").add();
	public static final Item leadHoe = new ItemSMMHoe(ToolMaterials.LEAD).setUnlocalizedName("leadHoe").setTextureName(Reference.MODID + ":" + "leadHoe").add();
	public static final Item leadSword = new ItemSMMSword(ToolMaterials.LEAD).setUnlocalizedName("leadSword").setTextureName(Reference.MODID + ":" + "leadSword").add();
	public static final Item obsidianPickaxe = new ItemSMMPickaxe(ToolMaterials.OBSIDIAN).setUnlocalizedName("obsidianPickaxe").setTextureName(Reference.MODID + ":" + "obsidianPickaxe").add();
	public static final Item obsidianAxe = new ItemSMMAxe(ToolMaterials.OBSIDIAN).setUnlocalizedName("obsidianAxe").setTextureName(Reference.MODID + ":" + "obsidianAxe").add();
	public static final Item obsidianShovel = new ItemSMMShovel(ToolMaterials.OBSIDIAN).setUnlocalizedName("obsidianShovel").setTextureName(Reference.MODID + ":" + "obsidianShovel").add();
	public static final Item obsidianHoe = new ItemSMMHoe(ToolMaterials.OBSIDIAN).setUnlocalizedName("obsidianHoe").setTextureName(Reference.MODID + ":" + "obsidianHoe").add();
	public static final Item obsidianSword = new ItemSMMSword(ToolMaterials.OBSIDIAN).setUnlocalizedName("obsidianSword").setTextureName(Reference.MODID + ":" + "obsidianSword").add();
	public static final Item endStonePickaxe = new ItemSMMPickaxe(ToolMaterials.ENDSTONE).setUnlocalizedName("endStonePickaxe").setTextureName(Reference.MODID + ":" + "endStonePickaxe").add();
	public static final Item endStoneAxe = new ItemSMMAxe(ToolMaterials.ENDSTONE).setUnlocalizedName("endStoneAxe").setTextureName(Reference.MODID + ":" + "endStoneAxe").add();
	public static final Item endStoneShovel = new ItemSMMShovel(ToolMaterials.ENDSTONE).setUnlocalizedName("endStoneShovel").setTextureName(Reference.MODID + ":" + "endStoneShovel").add();
	public static final Item endStoneHoe = new ItemSMMHoe(ToolMaterials.ENDSTONE).setUnlocalizedName("endStoneHoe").setTextureName(Reference.MODID + ":" + "endStoneHoe").add();
	public static final Item endStoneSword = new ItemSMMSword(ToolMaterials.ENDSTONE).setUnlocalizedName("endStoneSword").setTextureName(Reference.MODID + ":" + "endStoneSword").add();
	public static final Item sapphirePickaxe = new ItemSMMPickaxe(ToolMaterials.SAPPHIRE).setUnlocalizedName("sapphirePickaxe").setTextureName(Reference.MODID + ":" + "sapphirePickaxe").add();
	public static final Item sapphireAxe = new ItemSMMAxe(ToolMaterials.SAPPHIRE).setUnlocalizedName("sapphireAxe").setTextureName(Reference.MODID + ":" + "sapphireAxe").add();
	public static final Item sapphireShovel = new ItemSMMShovel(ToolMaterials.SAPPHIRE).setUnlocalizedName("sapphireShovel").setTextureName(Reference.MODID + ":" + "sapphireShovel").add();
	public static final Item sapphireHoe = new ItemSMMHoe(ToolMaterials.SAPPHIRE).setUnlocalizedName("sapphireHoe").setTextureName(Reference.MODID + ":" + "sapphireHoe").add();
	public static final Item sapphireSword = new ItemSMMSword(ToolMaterials.SAPPHIRE).setUnlocalizedName("sapphireSword").setTextureName(Reference.MODID + ":" + "sapphireSword").add();
	public static final Item topazPickaxe = new ItemSMMPickaxe(ToolMaterials.TOPAZ).setUnlocalizedName("topazPickaxe").setTextureName(Reference.MODID + ":" + "topazPickaxe").add();
	public static final Item topazAxe = new ItemSMMAxe(ToolMaterials.TOPAZ).setUnlocalizedName("topazAxe").setTextureName(Reference.MODID + ":" + "topazAxe").add();
	public static final Item topazShovel = new ItemSMMShovel(ToolMaterials.TOPAZ).setUnlocalizedName("topazShovel").setTextureName(Reference.MODID + ":" + "topazShovel").add();
	public static final Item topazHoe = new ItemSMMHoe(ToolMaterials.TOPAZ).setUnlocalizedName("topazHoe").setTextureName(Reference.MODID + ":" + "topazHoe").add();
	public static final Item topazSword = new ItemSMMSword(ToolMaterials.TOPAZ).setUnlocalizedName("topazSword").setTextureName(Reference.MODID + ":" + "topazSword").add();
	public static final Item jadePickaxe = new ItemSMMPickaxe(ToolMaterials.JADE).setUnlocalizedName("jadePickaxe").setTextureName(Reference.MODID + ":" + "jadePickaxe").add();
	public static final Item jadeAxe = new ItemSMMAxe(ToolMaterials.JADE).setUnlocalizedName("jadeAxe").setTextureName(Reference.MODID + ":" + "jadeAxe").add();
	public static final Item jadeShovel = new ItemSMMShovel(ToolMaterials.JADE).setUnlocalizedName("jadeShovel").setTextureName(Reference.MODID + ":" + "jadeShovel").add();
	public static final Item jadeHoe = new ItemSMMHoe(ToolMaterials.JADE).setUnlocalizedName("jadeHoe").setTextureName(Reference.MODID + ":" + "jadeHoe").add();
	public static final Item jadeSword = new ItemSMMSword(ToolMaterials.JADE).setUnlocalizedName("jadeSword").setTextureName(Reference.MODID + ":" + "jadeSword").add();
	public static final Item steelPickaxe = new ItemSMMPickaxe(ToolMaterials.STEEL).setUnlocalizedName("steelPickaxe").setTextureName(Reference.MODID + ":" + "steelPickaxe").add();
	public static final Item steelAxe = new ItemSMMAxe(ToolMaterials.STEEL).setUnlocalizedName("steelAxe").setTextureName(Reference.MODID + ":" + "steelAxe").add();
	public static final Item steelShovel = new ItemSMMShovel(ToolMaterials.STEEL).setUnlocalizedName("steelShovel").setTextureName(Reference.MODID + ":" + "steelShovel").add();
	public static final Item steelHoe = new ItemSMMHoe(ToolMaterials.STEEL).setUnlocalizedName("steelHoe").setTextureName(Reference.MODID + ":" + "steelHoe").add();
	public static final Item steelSword = new ItemSMMSword(ToolMaterials.STEEL).setUnlocalizedName("steelSword").setTextureName(Reference.MODID + ":" + "steelSword").add();
	public static final Item tanzanitePickaxe = new ItemSMMPickaxe(ToolMaterials.TANZANITE).setUnlocalizedName("tanzanitePickaxe").setTextureName(Reference.MODID + ":" + "tanzanitePickaxe").add();
	public static final Item tanzaniteAxe = new ItemSMMAxe(ToolMaterials.TANZANITE).setUnlocalizedName("tanzaniteAxe").setTextureName(Reference.MODID + ":" + "tanzaniteAxe").add();
	public static final Item tanzaniteShovel = new ItemSMMShovel(ToolMaterials.TANZANITE).setUnlocalizedName("tanzaniteShovel").setTextureName(Reference.MODID + ":" + "tanzaniteShovel").add();
	public static final Item tanzaniteHoe = new ItemSMMHoe(ToolMaterials.TANZANITE).setUnlocalizedName("tanzaniteHoe").setTextureName(Reference.MODID + ":" + "tanzaniteHoe").add();
	public static final Item tanzaniteSword = new ItemSMMSword(ToolMaterials.TANZANITE).setUnlocalizedName("tanzaniteSword").setTextureName(Reference.MODID + ":" + "tanzaniteSword").add();
	public static final Item apatitePickaxe = new ItemSMMPickaxe(ToolMaterials.APATITE).setUnlocalizedName("apatitePickaxe").setTextureName(Reference.MODID + ":" + "apatitePickaxe").add();
	public static final Item apatiteAxe = new ItemSMMAxe(ToolMaterials.APATITE).setUnlocalizedName("apatiteAxe").setTextureName(Reference.MODID + ":" + "apatiteAxe").add();
	public static final Item apatiteShovel = new ItemSMMShovel(ToolMaterials.APATITE).setUnlocalizedName("apatiteShovel").setTextureName(Reference.MODID + ":" + "apatiteShovel").add();
	public static final Item apatiteHoe = new ItemSMMHoe(ToolMaterials.APATITE).setUnlocalizedName("apatiteHoe").setTextureName(Reference.MODID + ":" + "apatiteHoe").add();
	public static final Item apatiteSword = new ItemSMMSword(ToolMaterials.APATITE).setUnlocalizedName("apatiteSword").setTextureName(Reference.MODID + ":" + "apatiteSword").add();
	public static final Item netherQuartzPickaxe = new ItemSMMPickaxe(ToolMaterials.NETHERQUARTZ).setUnlocalizedName("netherQuartzPickaxe").setTextureName(Reference.MODID + ":" + "netherQuartzPickaxe").add();
	public static final Item netherQuartzAxe = new ItemSMMAxe(ToolMaterials.NETHERQUARTZ).setUnlocalizedName("netherQuartzAxe").setTextureName(Reference.MODID + ":" + "netherQuartzAxe").add();
	public static final Item netherQuartzShovel = new ItemSMMShovel(ToolMaterials.NETHERQUARTZ).setUnlocalizedName("netherQuartzShovel").setTextureName(Reference.MODID + ":" + "netherQuartzShovel").add();
	public static final Item netherQuartzHoe = new ItemSMMHoe(ToolMaterials.NETHERQUARTZ).setUnlocalizedName("netherQuartzHoe").setTextureName(Reference.MODID + ":" + "netherQuartzHoe").add();
	public static final Item netherQuartzSword = new ItemSMMSword(ToolMaterials.NETHERQUARTZ).setUnlocalizedName("netherQuartzSword").setTextureName(Reference.MODID + ":" + "netherQuartzSword").add();
	public static final Item amethystPickaxe = new ItemSMMPickaxe(ToolMaterials.AMETHYST).setUnlocalizedName("amethystPickaxe").setTextureName(Reference.MODID + ":" + "amethystPickaxe").add();
	public static final Item amethystAxe = new ItemSMMAxe(ToolMaterials.AMETHYST).setUnlocalizedName("amethystAxe").setTextureName(Reference.MODID + ":" + "amethystAxe").add();
	public static final Item amethystShovel = new ItemSMMShovel(ToolMaterials.AMETHYST).setUnlocalizedName("amethystShovel").setTextureName(Reference.MODID + ":" + "amethystShovel").add();
	public static final Item amethystHoe = new ItemSMMHoe(ToolMaterials.AMETHYST).setUnlocalizedName("amethystHoe").setTextureName(Reference.MODID + ":" + "amethystHoe").add();
	public static final Item amethystSword = new ItemSMMSword(ToolMaterials.AMETHYST).setUnlocalizedName("amethystSword").setTextureName(Reference.MODID + ":" + "amethystSword").add();
	
	public static void initTools()
	{
		GameRegistry.registerItem(coalPickaxe, coalPickaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(coalAxe, coalAxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(coalShovel, coalShovel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(coalHoe, coalHoe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(coalSword, coalSword.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(emeraldPickaxe, emeraldPickaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(emeraldAxe, emeraldAxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(emeraldShovel, emeraldShovel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(emeraldHoe, emeraldHoe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(emeraldSword, emeraldSword.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(redstonePickaxe, redstonePickaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(redstoneAxe, redstoneAxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(redstoneShovel, redstoneShovel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(redstoneHoe, redstoneHoe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(redstoneSword, redstoneSword.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(lapisLazuliPickaxe, lapisLazuliPickaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(lapisLazuliAxe, lapisLazuliAxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(lapisLazuliShovel, lapisLazuliShovel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(lapisLazuliHoe, lapisLazuliHoe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(lapisLazuliSword, lapisLazuliSword.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(earthQuartzPickaxe, earthQuartzPickaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(earthQuartzAxe, earthQuartzAxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(earthQuartzShovel, earthQuartzShovel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(earthQuartzHoe, earthQuartzHoe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(earthQuartzSword, earthQuartzSword.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(copperPickaxe, copperPickaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(copperAxe, copperAxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(copperShovel, copperShovel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(copperHoe, copperHoe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(copperSword, copperSword.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(carbonPickaxe, carbonPickaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(carbonAxe, carbonAxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(carbonShovel, carbonShovel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(carbonHoe, carbonHoe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(carbonSword, carbonSword.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(silverPickaxe, silverPickaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(silverAxe, silverAxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(silverShovel, silverShovel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(silverHoe, silverHoe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(silverSword, silverSword.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(cobaltPickaxe, cobaltPickaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(cobaltAxe, cobaltAxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(cobaltShovel, cobaltShovel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(cobaltHoe, cobaltHoe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(cobaltSword, cobaltSword.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(rubyPickaxe, rubyPickaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(rubyAxe, rubyAxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(rubyShovel, rubyShovel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(rubyHoe, rubyHoe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(rubySword, rubySword.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(titaniumPickaxe, titaniumPickaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(titaniumAxe, titaniumAxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(titaniumShovel, titaniumShovel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(titaniumHoe, titaniumHoe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(titaniumSword, titaniumSword.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(hellishPickaxe, hellishPickaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(hellishAxe, hellishAxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(hellishShovel, hellishShovel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(hellishHoe, hellishHoe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(hellishSword, hellishSword.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(leadPickaxe, leadPickaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(leadAxe, leadAxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(leadShovel, leadShovel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(leadHoe, leadHoe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(leadSword, leadSword.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(obsidianPickaxe, obsidianPickaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(obsidianAxe, obsidianAxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(obsidianShovel, obsidianShovel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(obsidianHoe, obsidianHoe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(obsidianSword, obsidianSword.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(endStonePickaxe, endStonePickaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(endStoneAxe, endStoneAxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(endStoneShovel, endStoneShovel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(endStoneHoe, endStoneHoe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(endStoneSword, endStoneSword.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(sapphirePickaxe, sapphirePickaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(sapphireAxe, sapphireAxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(sapphireShovel, sapphireShovel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(sapphireHoe, sapphireHoe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(sapphireSword, sapphireSword.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(topazPickaxe, topazPickaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(topazAxe, topazAxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(topazShovel, topazShovel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(topazHoe, topazHoe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(topazSword, topazSword.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(jadePickaxe, jadePickaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(jadeAxe, jadeAxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(jadeShovel, jadeShovel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(jadeHoe, jadeHoe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(jadeSword, jadeSword.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(steelPickaxe, steelPickaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(steelAxe, steelAxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(steelShovel, steelShovel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(steelHoe, steelHoe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(steelSword, steelSword.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(tanzanitePickaxe, tanzanitePickaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(tanzaniteAxe, tanzaniteAxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(tanzaniteShovel, tanzaniteShovel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(tanzaniteHoe, tanzaniteHoe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(tanzaniteSword, tanzaniteSword.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(apatitePickaxe, apatitePickaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(apatiteAxe, apatiteAxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(apatiteShovel, apatiteShovel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(apatiteHoe, apatiteHoe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(apatiteSword, apatiteSword.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(netherQuartzPickaxe, netherQuartzPickaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(netherQuartzAxe, netherQuartzAxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(netherQuartzShovel, netherQuartzShovel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(netherQuartzHoe, netherQuartzHoe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(netherQuartzSword, netherQuartzSword.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(amethystPickaxe, amethystPickaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(amethystAxe, amethystAxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(amethystShovel, amethystShovel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(amethystHoe, amethystHoe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(amethystSword, amethystSword.getUnlocalizedName().substring(5));
	}
}
